### ISSUE TITLE
Recommend to add assertion for the value of "lamb" in CRFMNES init

### ISSUE THREAD

**Issue by Obliman** [nomuramasahir0/crfmnes#5]
I've noticed that if "lamb" is defined as an odd number it will result in a ValueError as it tries to split data unevenly (except for "3", which mysteriously works just fine).

My suggestion is to add this line to the CRFMNES __init__:
```
assert (lamb > 0 and lamb % 2 == 0), f"The value of 'lamb' must be an even, positive integer greater than 0"
```

**Comment by nomuramasahir0** [comment]
Thank you for the suggestion!
Yes, CR-FM-NES uses even number for lambda because it uses antithetic variates method, which reduces the variance of estimating natural gradient.
I accept the suggestion and will fix this later.

**Comment by nomuramasahir0** [comment]
Fixed. Thanks @Obliman!
